name: Preview channel
on:
  workflow_dispatch:
env:
  NODE_VERSION: 14.x
defaults:
  run:
    shell: bash
jobs:
  build_engine:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout branch develop
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm install
      - name: Build engine
        run: npm run build:engine
      - name: Store engine artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: dist/build/akos-engine
  build_editor:
    runs-on: ${{ matrix.os }}
    needs: [build_engine]
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout branch develop
        run: ls -l
