# TODO
# Fix engine exec permission

name: Preview channel
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build_engine:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout branch develop
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Install dependencies
        run: npm install
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path:  ~/.npm
          key: dep
      - name: Build engine
        run: npm run build:engine
      - name: Upload engine artifact
        uses: actions/upload-artifact@v2
        with:
          name: akos-engine
          path: dist/build/akos-engine/*
  build_editor:
    runs-on: ${{ matrix.os }}
    needs: [build_engine]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout branch develop
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Retrieve dependencies
        uses: actions/cache@v2
        with:
          path:  ~/.npm
          key: dep
      - name: Download engine artifacts
        uses: actions/download-artifact@v2
        with:
          path: dist/build
      - name: Clean engine directory
        run: rm -rf dist/build/akos-engine/.icon-ico
      - name: Build editor
        run: npm run build:editor
      - name: Upload editor
        uses: actions/upload-artifact@v2
        with:
          name: preview
          path: dist/release/*
          
        
